export default {
    panelWidth:16,
    panelHeight:20,
    nextWidth:6,
    level:[
        {
            score:0,
            duration:1500,
        },
        {
            score:100,
            duration:1200,
        },
        {
            score:300,
            duration:800,
        },
        {
            score:500,
            duration:300,
        }
    ]
}